# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=200)),
                ('user_2', models.CharField(max_length=200)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(max_length=200)),
                ('restaurant_picture', models.CharField(max_length=200)),
                ('meal_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_proposed_to', models.CharField(max_length=200)),
                ('user_proposed_from', models.CharField(max_length=200)),
                ('filled', models.BooleanField(default=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=200)),
                ('location_string', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('meal_time', models.DateTimeField()),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to=b'')),
                ('password_hash', models.CharField(max_length=30)),
                ('logged', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restful_api.User'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restful_api.Request'),
        ),
    ]
